//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int Id { get; set; }
        public string TieuDe { get; set; }
        public string TomTat { get; set; }
        public string Anh { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string TacGia { get; set; }
        public string ChuDe { get; set; }
    }
}
